### ISSUE TITLE
Server thread/ERROR Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for HolographicDisplays

### ISSUE THREAD

**Issue by KennethRhodes8213** [filoghost/HolographicDisplays#170] opened 2019-06-17 19:24 UTC
17.06 12:23:23 [Server] INFO ... 35 more 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?] 17.06 12:23:23 [Server] INFO }} 17.06 12:23:23 [Server] INFO methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}] 17.06 12:23:23 [Server] INFO fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}], 17.06 12:23:23 [Server] INFO Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={ 17.06 12:23:23 [Server] INFO ... 35 more 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?] 17.06 12:23:23 [Server] INFO Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 4782. 17.06 12:23:23 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:277) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:385) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:969) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:165) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:317) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:349) [spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:1103) ~[spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1396) ~[spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1423) ~[spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot.jar:git-Spigot-093165d-ba575a5] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?] 17.06 12:23:23 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?] 17.06 12:23:23 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?] 17.06 12:23:23 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?] 17.06 12:23:23 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?] 17.06 12:23:23 [Server] INFO java.lang.RuntimeException: Cannot retrieve entity from ID. 17.06 12:23:23 [Server] Server thread/ERROR Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for HolographicDisplays

**Comment by mcpanglei** [comment] 2019-06-23 01:16
me too

**Comment by sgdc3** [comment] 2019-06-23 21:58
Please use pastebin...

**Comment by EnderGamingFilms** [comment] 2019-06-24 23:40
Same https://pastebin.com/1h3SuRGA

**Comment by filoghost** [comment] 2019-06-25 11:02
Duplicate of https://github.com/filoghost/HolographicDisplays/issues/135

**Closed by filoghost** 2019-06-25 11:02 UTC
