### ISSUE TITLE
problem with holographicdisplays (show error in console)

### ISSUE THREAD

**Issue by Antonelloh** [filoghost/HolographicDisplays#248] opened 2020-01-14 22:16 UTC
http://prntscr.com/qnr8aw
Please, how i can fix it?

**Comment by filoghost** [comment] 2020-04-10 09:42
Duplicate of #250 (I know you submitted the issue before, but the other one is more detailed). Do you use InventiveTalent's GlowAPI too? Please comment on the other issue.

**Closed by filoghost** 2020-04-10 09:42 UTC
