### ISSUE TITLE
1.14.2 Error

### ISSUE THREAD

**Issue by salikaaa** [filoghost/HolographicDisplays#158] opened 2019-06-05 20:02 UTC
Server file: PaperSpigot 1.14.2
Holo plugin: HolographicDisplays 2.3.3 Latest dev version
Error message:
[16:03:35] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:225) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-63]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 285.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 32 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}], 
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 32 more
[16:03:35] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@68866282[
    a=285
    b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@2e1eab4d, net.minecraft.server.v1_14_R1.DataWatcher$Item@61ed17a4, net.minecraft.server.v1_14_R1.DataWatcher$Item@2c725c8d, net.minecraft.server.v1_14_R1.DataWatcher$Item@531523af, net.minecraft.server.v1_14_R1.DataWatcher$Item@80abe43, net.minecraft.server.v1_14_R1.DataWatcher$Item@153c8d1, net.minecraft.server.v1_14_R1.DataWatcher$Item@3f7b7a42, net.minecraft.server.v1_14_R1.DataWatcher$Item@45092e59, net.minecraft.server.v1_14_R1.DataWatcher$Item@182c781d, net.minecraft.server.v1_14_R1.DataWatcher$Item@7263e89, net.minecraft.server.v1_14_R1.DataWatcher$Item@636bed45, net.minecraft.server.v1_14_R1.DataWatcher$Item@6f1c7c97, net.minecraft.server.v1_14_R1.DataWatcher$Item@140b0df9, net.minecraft.server.v1_14_R1.DataWatcher$Item@226fbb87, net.minecraft.server.v1_14_R1.DataWatcher$Item@1e527b4a, net.minecraft.server.v1_14_R1.DataWatcher$Item@122644d3, net.minecraft.server.v1_14_R1.DataWatcher$Item@5e8ef7ab, net.minecraft.server.v1_14_R1.DataWatcher$Item@162cc7e, net.minecraft.server.v1_14_R1.DataWatcher$Item@c676f33]
  ]

[16:03:35] [Server thread/INFO]: XenoMC_[/188.143.15.107:8959] logged in with entity id 285 at ([world]166.74732673287474, 69.0, -186.42267567047583)
[16:03:35] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:391) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:351) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:199) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1025) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:389) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:282) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-63]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 285.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 34 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}], 
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 34 more
[16:03:35] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@3fb96efe[
    a=285
    b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@5473fd9c]
  ]

[16:03:35] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:646) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:625) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:70) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:79) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:134) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:276) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1229) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1089) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$31(PlayerChunkMap.java:657) ~[patched_1.14.2.jar:git-Paper-63]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$null$32(PlayerChunkMap.java:656) ~[patched_1.14.2.jar:git-Paper-63]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[patched_1.14.2.jar:git-Paper-63]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.14.2.jar:git-Paper-63]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$a$33(PlayerChunkMap.java:652) ~[patched_1.14.2.jar:git-Paper-63]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:512) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:96) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:331) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:288) ~[patched_1.14.2.jar:git-Paper-63]
	at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:148) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:326) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-63]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-63]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 289.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:236) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 63 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
  fields=[{modifiers=[required: 0, banned: 0], type=input instanceof interface java.util.Set}], 
  methods=[{modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: null}], paramCount=1}, {modifiers=[required: 0, banned: 0], return=Exact void, params=[{Type: class net.minecraft.server.v1_14_R1.Entity instanceof input, Index: 0}, {Type: int instanceof input, Index: 1}, {Type: int instanceof input, Index: 2}], paramCount=3}]
}}
	at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getEntityTrackerClass(MinecraftReflection.java:1548) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityTrackerEntry(EntityUtilities.java:175) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:211) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:640) ~[?:?]
	... 63 more
[16:03:35] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutSpawnEntityLiving@78d787d3[
    a=289
    b=ab514ec6-d379-49ac-b303-9a5a77aebb40
    c=1
    d=170.5
    e=70.07999999999998
    f=-185.5
    g=0
    h=0
    i=0
    j=2
    k=0
    l=2
    m=net.minecraft.server.v1_14_R1.DataWatcher@2334f9d0
    n=<null>
  ]

Fix please
Thanks,

**Comment by salikaaa** [comment] 2019-06-05 20:03
*
The error occurs when a player joins

**Comment by DjeyMute** [comment] 2019-06-10 16:12
I have the same error

**Comment by salikaaa** [comment] 2019-06-11 10:33
Delete the protocollib plugin.

**Comment by mcpanglei** [comment] 2019-06-23 01:15
me too

**Comment by filoghost** [comment] 2019-06-25 11:03
Duplicate of https://github.com/filoghost/HolographicDisplays/issues/135

**Closed by filoghost** 2019-06-25 11:03 UTC
