### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xipsaaahoy** [filoghost/HolographicDisplays#400] opened 2021-01-20 11:25 UTC
### Description
It just happers on my console

### How to reproduce
It happers somehow 

### Platform

- Server version (output of `/version`): 
![imagem](https://user-images.githubusercontent.com/74424349/105168539-2ef0bd00-5b12-11eb-87a6-8f138ffe8660.png)

- Holographic Displays version (check with `/hd`): 
![imagem](https://user-images.githubusercontent.com/74424349/105168570-344e0780-5b12-11eb-9a34-a33a68cb4caa.png)

- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
![imagem](https://user-images.githubusercontent.com/74424349/105168590-3b751580-5b12-11eb-950d-494fb93ff23b.png)

### Additional context
https://pastebin.com/A1RNkvCK - Error

**Comment by Kod3ntz** [comment] 2021-01-22 06:57
Also having this error. [https://pastebin.com/F7vgmvRg](https://pastebin.com/F7vgmvRg)

Purpur 1.16.5
HolographicDisplays 2.4.5
ProtocolLib 4.6.0-SNAPSHOT-b492
ViaVersion 3.2.1

**Comment by filoghost** [comment] 2021-01-24 14:16
Duplicate of #388

**Closed by filoghost** 2021-01-24 14:16 UTC
Labels: Bug
