### ISSUE TITLE
HolographicDisplay Error

### ISSUE THREAD

**Issue by t0xic1** [filoghost/HolographicDisplays#386] opened 2021-01-04 18:11 UTC
### Description
When spawning any MythicMobs mob from the default config spams this error.

### How to reproduce
Make a server and install following plugins
MythicMobs
Procollib
LibsDisguises
HolographicDisplays

1. Start the server
2. Type /mm mobs spawn SkeletalKnight
3. Wait for about 10-20 seconds for the error to appear

### Platform
- Holographic Displays version 2.4.5
- ProtocolLib version v4.6.0-SNAPSHOT-b491
- Spigot 1.16.4 R-0.1 SNAPSHOT

### Additional context
Error log:
https://pastebin.com/p0DU37Pu

**Comment by filoghost** [comment] 2021-01-06 16:24
Duplicate of #388 (keeping the most detailed one)

**Closed by filoghost** 2021-01-06 16:24 UTC
Labels: Bug
