### ISSUE TITLE
I can't see the holograms

### ISSUE THREAD

**Issue by Tanerx** [filoghost/HolographicDisplays#672] opened 2023-01-11 19:32 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

Creating hologram is working fine with Build #232 (Sat Oct 01 20:32:16 UTC 2022) Starting with Build #233 and all after builds i can't see any hologram in game even stable release of 3.0.0.  This for 1.18.2 server. Created holograms with 3.0.0 can't see until i downgrade the plugin Build #232
For 1.19.3 server I used latest dev build 3.0.1 same issue.

### How to reproduce

Create any in game hologram
/hd create example &7&lColor test&r: &uRainbow

### Server version

Paper version git-Paper-375 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7a64b85)

### Holographic Displays version

HolographicDisplays version 3.0.1-SNAPSHOT-b244

### Installed plugins that allow players to join with multiple Minecraft versions

Plugins (3): HolographicDisplays, ProtocolLib, Vault

### Additional information

When testing 1.19.3 server i used unmodded 1.19.3 client. 
Full 1.19.3 server log if you need https://pastebin.com/p0WvZ0nN

**Comment by filoghost** [comment] 2023-04-29 16:08
Wait, why would you set view distance to 0? View distance should be greater or equal to simulation distance.

**Comment by Tanerx** [comment] 2023-04-29 16:41
> Wait, why would you set view distance to 0? View distance should be greater or equal to simulation distance. Is there a legit use for that? I might not be aware.

Custom game with a adventure mode server. Ticking chunks doesn't need in this situation. Almost no server would ever need to do this anyway. It's a rare event.

**Comment by filoghost** [comment] 2023-04-30 13:30
@Tanerx ok I think I can close this then. Thank for finding the cause.

**Closed by filoghost** 2023-04-30 13:30 UTC
Labels: Bug
