### ISSUE TITLE
onPacketSending(PacketEvent) for HolographicDisplays: Not implemented

### ISSUE THREAD

**Issue by HeavenCrafter** [filoghost/HolographicDisplays#264] opened 2020-02-29 16:51 UTC
This error seems to be mostly on 1.12.2 (Not sure about other versions though)
I was originally running this on a server with ProtocolSupport and ViaVersion and removed them thinking that it was the cause of the problem but even when I did, it was still occuring.
I am running on the latest version of ProtocolLib and HolographicDisplay.
I did also contact the developer of TrainCarts and all he said was that something is not implemented in the NMS API for my server version.
Similiar error with #250

Error occuring with TC-Coaster/TrainCarts Coaster.
Heres the full [stacktrace](https://hastebin.com/uraraginug.rb)

This current error is only one part of it.

> [11:52:06 ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Not implemented
at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:189) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:144) ~[HolographicDisplays.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.5.0]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1142) [server.jar:git-Spigot-79a30d7-acbc348]
at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen26cd1671.invoke(Unknown Source) [?:?]
at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:132) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1561) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1682) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.generated.net.minecraft.server.PlayerConnectionHandle$impl.sendPacket(Unknown Source) [?:?]
at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.sendPacket(ProtocolLibPacketHandler.java:148) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.common.utils.PacketUtil.sendPacket(PacketUtil.java:122) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.common.utils.PacketUtil.sendPacket(PacketUtil.java:109) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.particles.TrackParticleArrow.onStateUpdated(TrackParticleArrow.java:146) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.tracks.TrackNode.onStateUpdated(TrackNode.java:390) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.setEditing(PlayerEditState.java:425) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.selectNode(PlayerEditState.java:403) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.createNewNode(PlayerEditState.java:1013) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.createTrack(PlayerEditState.java:984) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.updateEditing(PlayerEditState.java:654) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.editor.PlayerEditState.update(PlayerEditState.java:624) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.TCCoasters$1.run(TCCoasters.java:264) [TCCoasters-1.15.2-v1.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [server.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
> [11:52:06 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayOutEntityMetadata@82d947ce[
a=-1
b=[net.minecraft.server.v1_12_R1.DataWatcher$Item@76641e3d, net.minecraft.server.v1_12_R1.DataWatcher$Item@6fd34c4]
> [11:52:06 ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Not implemented
at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:189) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[HolographicDisplays.jar:?]
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:129) ~[HolographicDisplays.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.5.0]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.5.0]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1142) [server.jar:git-Spigot-79a30d7-acbc348]
at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen26cd1671.invoke(Unknown Source) [?:?]
at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:132) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1561) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1682) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.generated.net.minecraft.server.PlayerConnectionHandle$impl.sendPacket(Unknown Source) [?:?]
at com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler.sendPacket(ProtocolLibPacketHandler.java:148) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.common.utils.PacketUtil.sendPacket(PacketUtil.java:122) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.common.utils.PacketUtil.sendPacket(PacketUtil.java:109) [BKCommonLib-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.particles.TrackParticleArrow.makeVisibleFor(TrackParticleArrow.java:173) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.particles.TrackParticle.changeVisibility(TrackParticle.java:53) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.particles.TrackParticleWorld.update(TrackParticleWorld.java:175) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.particles.TrackParticleWorld.updateAll(TrackParticleWorld.java:107) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.world.CoasterWorldImpl.updateAll(CoasterWorldImpl.java:96) [TCCoasters-1.15.2-v1.jar:?]
at com.bergerkiller.bukkit.coasters.TCCoasters$1.run(TCCoasters.java:243) [TCCoasters-1.15.2-v1.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [server.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-acbc348]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
> [11:52:06 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayOutSpawnEntity@24af3738[
a=222
b=3d331ae3-2d69-4ba5-8bcc-d5c2d7b0be52
c=-1018.5235783196862
d=78.06610497471318
e=184.73339284054939
f=0
g=0
h=0
i=0
j=0
k=78
l=0

**Comment by filoghost** [comment] 2020-04-11 21:43
Duplicate of #250 (should be fixed anyhow)

**Closed by filoghost** 2020-04-11 21:43 UTC
