### ISSUE TITLE
onPacketSending(PacketEvent): Cannot retrieve entity from ID

### ISSUE THREAD

**Issue by badbones69** [filoghost/HolographicDisplays#135] opened 2019-05-09 13:54 UTC
I was testing out the 1.14 version of the plugin and got an error in console when I started my envoy. It doesn't seem to be coming from mine I do not believe so I'll just leave this error here for you. If it seems it's my plugin just let me know.

Error: https://pastebin.com/9Cm7V4Xm

My Plugin's code: https://github.com/badbones69/Crazy-Envoy/tree/0936c4bbde832444e7822b9a5a4aafb83539398f

My hook into HD: https://github.com/badbones69/Crazy-Envoy/blob/0936c4bbde832444e7822b9a5a4aafb83539398f/src/main/java/me/badbones69/crazyenvoy/multisupport/MVdWPlaceholderAPISupport.java

Build from Jenkins: https://ci.filoghost.me/job/HolographicDisplays/61/

**Comment by sgdc3** [comment] 2019-05-12 22:14
@badbones69 what's your ProtocolLib build number?

**Comment by badbones69** [comment] 2019-05-13 14:45
Version: 4.4.0-b421

**Comment by andfont** [comment] 2019-05-19 10:14
if I have the same error and I can not activate server until it is solved I use the last protocollib etc .. exactly the same please solve this error thank you very much great work xD

**Comment by filoghost** [comment] 2019-05-30 16:59
For the time being, it seems that you just to update ProtocolLib and keep up with the latest dev builds.

**Comment by MeesterMaarten** [comment] 2019-06-11 18:40
I'm receiving the same error with the latest HolographicDisplays build and the 'UltimateStacker' plugin: Spawner Holograms. Is this problem going to be solved?
Thanks in advance!

**Comment by MeesterMaarten** [comment] 2019-06-19 17:18
I'm using the latest ProtocolLib-build available, but still receiving the error @filoghost. Is a Hologram-build for this problem going to be released? It seems that alot of Players are reporting this error on GITHub.

Thanks in advance!

**Comment by filoghost** [comment] 2019-06-25 11:01
@MeesterMaarten can you please provide the updated error with the latest dev builds of both Holographic Displays and Protocol Lib?

**Comment by filoghost** [comment] 2019-06-25 11:04
For anyone being redirected here from other duplicate issues, this is the correct link for Protocol Lib dev builds: http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/

**Comment by mibby** [comment] 2019-07-02 20:06
Paper dev 122 (Spigot 1.14.3)
HolographicDisplay dev 84 (commit: be96a5c)
ProtocolLib Gradle dev 9

@filoghost I'm receiving this error as well with the latest dev builds of both ProtocolLib and HolographicDisplay.

**Comment by filoghost** [comment] 2019-07-12 06:51
@mibby It's still caused by Citizens, I will check if I need to manually exclude their entities or they're fixing it.

**Comment by bundabrg** [comment] 2019-07-12 11:22
References: https://github.com/CitizensDev/Citizens2/issues/1858

I'm getting the same issue. A very quick check of the Citizens codebase seems to indicate that the real error is that the field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker#tracker is being set to something that is not assignable. The relevant line from the sun reflect code (because the actual thrown error is misleading) is:

https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/reflect/UnsafeFieldAccessorImpl.java#L58

```
    protected void ensureObj(Object o) {
        // NOTE: will throw NullPointerException, as specified, if o is null
        if (!field.getDeclaringClass().isAssignableFrom(o.getClass())) {
            throwSetIllegalArgumentException(o);
        }
    }
```

A dump of my exception is:
```
07:11:24 [INFO] [paper-1.14] [07:11:24 ERROR]: [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
07:11:24 [INFO] [paper-1.14] java.lang.RuntimeException: Cannot retrieve entity from ID.
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEnt
ityMetadata.java:65) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1552) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1525) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:391) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:351) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:199) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1070) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:476) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:370) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-129]
07:11:24 [INFO] [paper-1.14]     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
07:11:24 [INFO] [paper-1.14] Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 27.
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
07:11:24 [INFO] [paper-1.14]     ... 34 more
07:11:24 [INFO] [paper-1.14] Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
07:11:24 [INFO] [paper-1.14]     ... 34 more
07:11:24 [INFO] [paper-1.14] Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
07:11:24 [INFO] [paper-1.14]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_171]
07:11:24 [INFO] [paper-1.14]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_171]
07:11:24 [INFO] [paper-1.14]     at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_171]
07:11:24 [INFO] [paper-1.14]     at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_171]
07:11:24 [INFO] [paper-1.14]     at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_171]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
07:11:24 [INFO] [paper-1.14]     at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
07:11:24 [INFO] [paper-1.14]     ... 34 more
07:11:24 [INFO] [paper-1.14] [07:11:24 ERROR]: Parameters:
07:11:24 [INFO] [paper-1.14]   net.minecraft.server.v1_14_R1.PacketPlayOutEntityMetadata@35607c30[
07:11:24 [INFO] [paper-1.14]     a=27
07:11:24 [INFO] [paper-1.14]     b=[net.minecraft.server.v1_14_R1.DataWatcher$Item@78b82462]
07:11:24 [INFO] [paper-1.14]   ]
```

My plugins:
```
shared/plugins/1.14$ ls -al | tr -s " " | cut -d " " -f 9- | grep -v ^\\.

ActionHealth.jar -> ../all/ActionHealth-3.3.0.jar
BetonQuest.jar -> ../all/BetonQuest.jar
citizens.jar -> ../all/Citizens-2.0.25-b1721.jar
CoreProtect.jar -> ../all/CoreProtect-2.17.4.jar
dynmap.jar -> ../all/Dynmap-3.0-SNAPSHOT-spigot.jar
EffectLib.jar -> ../all/EffectLib-6.1.jar
FastLoginBukkit.jar -> ../all/FastLoginBukkit-build885.jar
Harbor.jar -> ../all/Harbor-1.5.jar
HeadsPlus.jar -> ../all/HeadsPlus-6.3.1.jar
Holograms.jar -> ../all/Holograms-2.7.jar
HolographicDisplays.jar -> ../all/HolographicDisplays-2.3.3-SNAPSHOT-b84.jar
LuckPerms-Bukkit.jar -> ../all/LuckPerms-Bukkit-4.4.25.jar
MySkin.jar -> ../all/MySkin-2.7.jar
NPCDestinations.jar -> ../all/NPCDestinations-Plugin-2.3.0-snapshot.jar
PlaceholderAPI.jar -> ../all/PlaceholderAPI-2.10.2.jar
ProtocolLib.jar -> ../all/ProtocolLib-b9.jar
UltimateChat.jar -> ../all/UltimateChat-1.8.9-b224-Universal.jar
Vault.jar -> ../all/Vault-1.7.2.jar
worldedit.jar -> ../all/worldedit-bukkit-7.0.0-SNAPSHOT-20190528.jar
WorldGuardExtraFlags.jar -> ../all/WorldGuardExtraFlags-4.1.2.jar
worldguard-legacy.jar -> ../all/worldguard-legacy-7.0.0-SNAPSHOT-20190528.jar
WorldResourcepacks.jar -> ../all/WorldResourcepacks-271.jar
```

**Comment by mcmonkey4eva** [comment] 2019-07-16 19:18
The relevant code in Citizens:
https://github.com/CitizensDev/Citizens2/blob/master/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/util/PlayerlistTracker.java#L21

```java
public class PlayerlistTracker extends PlayerChunkMap.EntityTracker {
    private final PlayerChunkMap map;
    private final Entity tracker;
```

The overridden code in NMS:

```java
    public class EntityTracker {
        private final EntityTrackerEntry trackerEntry;
        private final Entity tracker;
```

Code in ProtocolLib that threw the exception: 
https://github.com/dmulloy2/ProtocolLib/blob/gradle/src/main/java/com/comphenix/protocol/injector/EntityUtilities.java#L200-L216
```java
trackerField = Accessors.getFieldAccessor(trackerEntry.getClass(), "tracker", true);
// ...
tracker = trackerField.get(trackerEntry); // Exception here
```
Which tracks from there into here: https://github.com/dmulloy2/ProtocolLib/blob/gradle/src/main/java/com/comphenix/protocol/reflect/accessors/DefaultFieldAccessor.java#L15

I'm not completely sure about this, but I think `trackerField` got set to the Citizens class's field (by way of the first tracker being passed into it being one generated by Citizens), and is then being used to read against vanilla instances of the class (which are of course incompatible with that reflection lookup). The solution would be to replace `trackerEntry.getClass()` in the linked ProtocolLib code with `PlayerChunkMap.EntityTracker.class` or an equivalent value like a `Class.forName` call (ie: explicitly use the class it's meant to work with, rather than trying to dynamically hack it).

This would place the issue resolution into ProtocolLib's code so I'll cc @dmulloy2

**Comment by bundabrg** [comment] 2019-07-29 08:35
It looks like trackerEntry is assigned differently with 1.14 than below. My guess is the actual fault lies somewhere in here. Just noting so I can look at it in a bit.

https://github.com/dmulloy2/ProtocolLib/blob/gradle/src/main/java/com/comphenix/protocol/injector/EntityUtilities.java#L136-L163

**Comment by mibby** [comment] 2019-08-01 02:03
@filoghost Any possible update or workaround following @mcmonkey4eva's response? :(

Still occurring for me.
https://paste.ubuntu.com/p/KyVpdxcTDq/

Paper dev 153 (Spigot 1.14.4)
ProtocolLib-Gradle dev 9
HolographicDisplays dev 85
Citizens dev 1737

**Comment by filoghost** [comment] 2019-08-11 16:36
I tried to develop a workaround (https://github.com/filoghost/HolographicDisplays/commit/ffb868093067a7f049ccbf6f075cad5ab0bb98a8) for both of these bugs (the one already fixed in newer ProtocolLib versions, and the one related to Citizens). Try the latest dev build: https://ci.codemc.org/job/filoghost/job/HolographicDisplays

I was not able to reproduce the bug with Citizens, please let me know if it's fixed or not.

_The bug still has to be fixed in ProtocolLib._

**Comment by Dinoosawruss** [comment] 2019-08-12 11:38
@filoghost Yes, the latest build fixes it

**Closed** 2019-08-21 19:07 UTC

**Comment by LoneDev6** [comment] 2019-11-25 13:23
I still have this problem in my plugin, did you manage to fix?

**Comment by peterjgordon** [comment] 2019-11-25 14:10
filoghost's workaround, mentioned in his last comment, is probably the best solution for now. Hopefully there'll be a fix in protocollib soon though...

**Comment by LoneDev6** [comment] 2019-11-25 14:24
Strange thing is that only sometimes this bug occurs.
After a server restart issue is vanished
