### ISSUE TITLE
Server version not supported error message

### ISSUE THREAD

**Issue by sugonmad** [filoghost/HolographicDisplays#530] opened 2021-11-30 23:19 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

The error message displayed when the server version is not supported says the plugin is only supported up to Spigot 1.16.4, while it is supported up to 1.17. 

### How to reproduce

1. Run a server on Spigot 1.18
2. Check the error message

### Server version

1.18 (sorry cant copy the cmd)

### Holographic Displays version

2.4.9

### ProtocolLib version (if installed)

null

### Installed plugins that allow players to join with multiple Minecraft versions

null

**Comment by filoghost** [comment] 2021-12-01 20:02
Duplicate of #529

**Closed by filoghost** 2021-12-01 20:02 UTC
Labels: Bug
