### ISSUE TITLE
HolographicDisplays BUG & Paper

### ISSUE THREAD

**Issue by kioging** [filoghost/HolographicDisplays#408] opened 2021-01-25 04:41 UTC
### Platform

- Server version (output of `/version`): 
- Holographic Displays version (check with `/hd`): 
- ProtocolLib version, if installed (check with `/protocol version`): 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 

### Additional context

Description
So my server refreshes the console from time to time and reports errors, hoping to be solved.

How to reproduce
The error message is as follows：
[XX:XX:XX ERROR]: [HolographicDisplays] Unhandled exception number 65536 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: com/comphenix/net/sf/cglib/proxy/Factory
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:87) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[?:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[?:git-Paper-443]
        at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:287) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:269) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2432) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2329) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2042) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2063) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:856) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:734) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-443]
        at java.lang.Thread.run(Thread.java:834) [?:?]

Platform
 This server is running Paper version git-Paper-443 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Server is running Holographic Displays v2.4.5 by filoghost
ProtocolLib v4.6.0-Development-b492

**Comment by filoghost** [comment] 2021-01-26 12:32
Duplicate of #388

**Closed by filoghost** 2021-01-26 12:32 UTC
Labels: Bug
