### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Plutoren** [filoghost/HolographicDisplays#245] opened 2020-01-01 03:31 UTC
I am using HD 2.4.0 and if you think it's a good idea to try the snapshot on a production server, I will.
Paper-235 1.14.4

I recently had an issue with essentials baltop destroying my ram and resolved that issue but while I was investigating that issue I couldn't help but notice holographic displays was just as bad of a ram eater.

Basically my ram is being slowly eaten up by HolographicDisplays creating thousands of "ArmorStand" instances in ram. When I start my server there's something like 2k, after 24hours there's 250k+

Here's a heap summary after around 24 hours.
https://sparkprofiler.github.io/#G0lTDzpNEJ
https://i.gyazo.com/24087cbd338b65a7f91c7f87a37b5cb1.png

Here's what that data looks like through java memory analyzer.
https://i.gyazo.com/25191005639773f07f3ce4bcc229fbaa.png
https://i.gyazo.com/2f0893fb56871476af02ae7395b476d9.png

I have tons of holograms, maybe 100-200 in and around my server across several worlds. It's not a huge issue if I restart every day or two but I'd like to resolve this as it eventually causes major lag with my garbage collection getting spammed every few seconds.

If you need anything else please let me know.

**Comment by filoghost** [comment] 2020-01-10 14:26
Hello, since it doesn't normally happen (I would expect way more reports otherwise) I assume it could be caused by another plugin either directly (for example, holding entities in memory) or indirectly (making HolographicDisplays refresh chunks too often, for example).

It could be Essentials that is holding those entities in memory.

Try removing Essentials, and other plugins until you find the one causing it, or please send me the file for the Java memory analyzer.

**Comment by Plutoren** [comment] 2020-01-10 17:07
I didn't really put 2 and 2 together until you mentioned it is likely another plugin but I recently removed my "UltimateKits" plugin in favor of making my own custom kits plugin and since making that change the problem mentioned above has not reoccurred. The number of holograms in memory has not risen at all during almost 6 days of uptime. Clearly the kits plugin was an issue.

For the record I was not using the hologram enabled features of the plugin but I do believe that the plugin constantly refreshed chunks and it certainly had a hologram feature.

**Comment by filoghost** [comment] 2020-01-12 15:51
Can you please share a link to that plugin? I would like to see if there's something that should be fixed in Holographic Displays.

**Comment by Plutoren** [comment] 2020-01-15 20:06
This is the plugin I was using: https://songoda.com/marketplace/product/ultimatekits-when-kits-and-crates-merge.14 
If you add my discord Plutoren#0001 I can share the entire heap dump I suspect it likely has some level of private data hidden in its depths so I would rather not share it here.

**Comment by filoghost** [comment] 2020-01-19 20:40
Yes, it contains private data most likely. I've sent you a request for discord.

**Comment by filoghost** [comment] 2020-01-26 13:16
After investigating, it looks like the entities weren't being removed by Spigot/Paper (I don't know if the issue is caused by Paper) even when marked as "dead". Could be caused by this: https://hub.spigotmc.org/jira/browse/SPIGOT-5228

**Closed by filoghost** 2020-01-26 13:16 UTC
