### ISSUE TITLE
Lag via chunk unloading

### ISSUE THREAD

**Issue by Alexz1008** [filoghost/HolographicDisplays#220] opened 2019-09-12 04:14 UTC
I've been hunting down this issue for a while now, and I think I've managed to pin it down. I have over 100 plugins, but I've narrowed down that the issue appears to happen with the following plugins:

Essentials, Multiverse, Serversigns, Mythicmobs, Holographicdisplays

I'm not sure if ALL of those plugins are necessary, but I do know that removing HolographicDisplays fixes it.

The issue itself is that server TPS drops dramatically (even if no players are online) for no real reason. From an earlier issue, someone suggested keeping chunks loaded that had holographic displays in them, and this fixed the issue for me, but I have holographic displays scattered everywhere and would prefer if the issue was just fixed by the plugin author if possible as I'd rather not have hundreds of chunks loaded permanently. I know that the Holograms plugin had a similar issue and made a fix for it, so I am confident there is a way to fix it for this plugin as well.

**Comment by sgdc3** [comment] 2019-10-14 10:04
Please provide timings v2 reports

**Comment by MiroTcz** [comment] 2019-10-15 07:30
[https://timings.aikar.co/?id=a36d3b30d8fa45b8ab1bc910a9cc59fa](url)

**Comment by Trikolon** [comment] 2019-10-20 11:22
Duplicate of #191 ?

**Comment by filoghost** [comment] 2019-10-21 10:02
@MiroTcz Unless I'm missing something from the timings, I don't see any lag related to Holographic Displays in your reports. @Alexz1008 if you can provide an additional timings, please do so in the issue #191, I'm closing this one.

**Closed by filoghost** 2019-10-21 10:02 UTC
