### ISSUE TITLE
IllegalArgumentException with new 1.13 materials

### ISSUE THREAD

**Issue by FreeWall** [filoghost/HolographicDisplays#99] opened 2018-08-27 15:18 UTC
I got this exception by calling `hologram.setItemLine(int, ItemStack)` with any new 1.13 material.

CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
HolographicDisplays-2.3.0-SNAPSHOT (Build 29)

```
java.lang.IllegalArgumentException: itemStack's material cannot be AIR
	at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:13) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.setItemStack(CraftItemLine.java:40) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.line.CraftItemLine.<init>(CraftItemLine.java:29) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.insertItemLine(CraftHologram.java:150) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.CraftHologram.insertItemLine(CraftHologram.java:26) ~[?:?]
```

**Comment by filoghost** [comment] 2018-08-31 10:47
This is caused by the plugin not having "api-version: 1.13" in plugin.yml. Will be fixed soon.

**Comment by filoghost** [comment] 2018-08-31 11:46
Should be fixed in https://github.com/filoghost/HolographicDisplays/commit/4d100e59c90b3081deeeafe330a39e40ed387c11 please try a new build

**Closed by filoghost** 2018-08-31 11:46 UTC
