### ISSUE TITLE
Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for HolographicDisplays

### ISSUE THREAD

**Issue by VenixMC** [filoghost/HolographicDisplays#409] opened 2021-01-25 13:34 UTC
### Description
This error message show on my console sometime

### Platform

- Server version (output of `/version`): This server is running CraftBukkit version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): Server is running Holographic Displays v2.4.5 by filoghost
- ProtocolLib version, if installed (check with `/protocol version`): ProtocolLib v4.6.0-SNAPSHOT-b492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): yes

**Comment by filoghost** [comment] 2021-01-26 12:32
Duplicate of #388

**Closed by filoghost** 2021-01-26 12:32 UTC
Labels: Bug
