### ISSUE TITLE
[HolographicDisplays] Unexpected error while modifying the channel pipeline.

### ISSUE THREAD

**Issue by andrewkm** [filoghost/HolographicDisplays#720] opened 2024-01-12 23:53 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

https://pastebin.com/raw/MZDKHstM

### How to reproduce

https://pastebin.com/raw/MZDKHstM

### Server version

Paper 1.20.4 Build 385

### Holographic Displays version

https://github.com/filoghost/HolographicDisplays/commit/07968520f04971e4626a9fc7ac7173dc655a6319

**Comment by filoghost** [comment] 2024-01-27 15:12
I attempted to fix this in the latest version, please give it a try. Unfortunately I don't know how to reproduce the bug.

**Comment by filoghost** [comment] 2024-01-27 15:14
I'm closing this as it's a duplicate of #712, please reply there.

**Closed by filoghost** 2024-01-27 15:14 UTC
Labels: Bug
