### ISSUE TITLE
Hex colors

### ISSUE THREAD

**Issue by ChExpress3** [filoghost/HolographicDisplays#582] opened 2022-02-07 19:16 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

The plugin not work with hex colors

### How to reproduce

1. create a hologram
2. put in &<hex code>
3. not work

### Server version

This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)

### Holographic Displays version

HolographicDisplays version 3.0.0-SNAPSHOT

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

**Comment by filoghost** [comment] 2022-10-08 10:51
The problem is that it gets interpreted as placeholder (the opening and closing curly braces). Use `\` before to escape the characters, e.g. `\{§r &#1D8348ciao &6&l&m\}`

**Closed** 2024-01-26 21:51 UTC
Labels: Bug
