### ISSUE TITLE
1.14.2 holograms load before the world loads

### ISSUE THREAD

**Issue by Sikatsu** [filoghost/HolographicDisplays#154] opened 2019-06-04 09:01 UTC
Hey, holograms in my Creative world no longer work as of 1.14.2.

Here is the startup log:

https://pastebin.com/P3mnykRG

**Comment by filoghost** [comment] 2019-06-04 13:28
Duplicate of https://github.com/filoghost/HolographicDisplays/issues/141

**Closed by filoghost** 2019-06-04 13:28 UTC
