### ISSUE TITLE
error with holographicdisplays 2.4.1

### ISSUE THREAD

**Issue by PhanaticD** [filoghost/HolographicDisplays#261] opened 2020-02-14 15:41 UTC
```
[10:39:15 ERROR]: [HolographicDisplays] Unhandled exception number 512 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Not implemented
        at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:189) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:129) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:209) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:172) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1479) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:376) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:213) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1443) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:632) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:315) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:356) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2103) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:147) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:271) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-653]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[10:39:21 ERROR]: [HolographicDisplays] Unhandled exception number 1024 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.IllegalStateException: Not implemented
        at com.gmail.filoghost.holographicdisplays.nms.interfaces.NMSManager.getEntityFromID(NMSManager.java:42) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.getEntity(ProtocolLibHookImpl.java:189) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.access$000(ProtocolLibHookImpl.java:55) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:144) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:209) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:172) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1506) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1479) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:324) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:330) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.d(EntityTrackerEntry.java:297) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.track(EntityTrackerEntry.java:239) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.EntityTracker.updatePlayers(EntityTracker.java:175) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1123) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-653]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-653]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by filoghost** [comment] 2020-04-10 15:18
Duplicate of #250 (please leave any additional comments there).

**Closed by filoghost** 2020-04-10 15:18 UTC
