### ISSUE TITLE
WARNS spamming in console randomly

### ISSUE THREAD

**Issue by axemwa** [filoghost/HolographicDisplays#112] opened 2018-11-18 06:09 UTC
https://pastebin.com/r4794vvF

**Comment by sgdc3** [comment] 2018-11-18 10:39
God, please use pastebin

**Comment by axemwa** [comment] 2018-11-18 11:32
Oops sorry

**Comment by filoghost** [comment] 2018-12-13 14:05
Looks like a duplicate of #115, please see if you can find a fix here: https://github.com/PaperMC/Paper/issues/1302

**Closed by filoghost** 2018-12-13 14:05 UTC
