### ISSUE TITLE
Error on join,leave, at random moment

### ISSUE THREAD

**Issue by steveq7** [filoghost/HolographicDisplays#387] opened 2021-01-04 18:28 UTC
### Description

HolographicDisplays] Unhandled exception number 16384 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.NoClassDefFoundError: com/comphenix/net/sf/cglib/proxy/Factory
at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:87) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:293) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:249) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:225) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1709) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.sendPlayerPacket(EntityTrackerEntry.java:49) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.a(EntityTrackerEntry.java:201) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.EntityTrackerEntry.tick(EntityTrackerEntry.java:75) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2052) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2063) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:865) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:460) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-388]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-388]
at java.lang.Thread.run(Thread.java:834) [?:?]

### How to reproduce

on player join
on player leave
or at random times

### Platform

- Server version (output of `/version`):  1.16.4 paper 388
- Holographic Displays version (check with `/hd`): 2.4.5 
- ProtocolLib version, if installed (check with `/protocol version`): #492
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): viaversion

**Comment by Kismalax** [comment] 2021-01-05 00:28
Seems like incompatibility with this ProtocolLib change: [https://github.com/dmulloy2/ProtocolLib/commit/b54dd49426f1c4cb5a15d1702a4803af1846847e](Link)

The last ProtocolLib build which is not affected is #490

**Comment by filoghost** [comment] 2021-01-06 16:24
Duplicate of #388 (keeping the most detailed one)

**Closed by filoghost** 2021-01-06 16:24 UTC
Labels: Bug
