### ISSUE TITLE
v3.0.0 not workin on 1.8.2

### ISSUE THREAD

**Issue by EvilInsid** [filoghost/HolographicDisplays#590] opened 2022-03-08 09:53 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

08.03 04:40:50 [Server] INFO Enabling HolographicDisplays v3.0.0-SNAPSHOT-b202
08.03 04:40:50 [Server] INFO Fatal error while enabling HolographicDisplays v3.0.0-SNAPSHOT-b202:
08.03 04:40:50 [Server] INFO Holographic Displays only supports Spigot from 1.8 to 1.18.
08.03 04:40:50 [Server] INFO The plugin has been disabled.

### How to reproduce

install holographic Displays v3.0.0 
Paperspigot 1.18.2

### Server version

PaperSpigot 1.18.2 w/Aikar's Flags

### Holographic Displays version

v3.0.0

### Additional information

cant go back to 1.18.1 ....

**Comment by filoghost** [comment] 2022-03-08 20:54
Duplicate of #588

**Closed by filoghost** 2022-03-08 20:54 UTC
Labels: Bug

**Comment by EvilInsid** [comment] 2022-03-08 21:04
Hello, i read that thread and they are getting a different error to me? Sorry i didnt think it was a duplicate

How do fix the problem?

**Comment by filoghost** [comment] 2022-03-08 22:26
Just update to the latest dev build.

**Comment by EvilInsid** [comment] 2022-03-09 06:59
08.03 04:40:50 [Server] INFO Enabling HolographicDisplays v3.0.0-SNAPSHOT-b202

i am using the latest dev build

**Comment by james090500** [comment] 2022-03-10 10:50
> 08.03 04:40:50 [Server] INFO Enabling HolographicDisplays v3.0.0-SNAPSHOT-b202
> 
> i am using the latest dev build

Latest dev is 204.
https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by EvilInsid** [comment] 2022-03-10 19:49
Thank you james!
