### ISSUE TITLE
Slime entity no longer working due to override of slimeHolographicDisplays

### ISSUE THREAD

**Issue by timbru31** [filoghost/HolographicDisplays#44] opened 2016-12-24 12:11 UTC
Hi,

your NMS code breaks the slime spawner or any other plugin relying on EntityTypes.b (RegistryMaterials of MinecraftKey and EntityClass), since you are overwriting the existing entry with the ID 55 (which is Slime).
Could you instead register an ID that was previously null? There are many IDs not yet used, since NMS breaks anyways you should be safe to use a non-existing ID.

See: https://github.com/filoghost/HolographicDisplays/blob/master/HolographicDisplays/Plugin/com/gmail/filoghost/holographicdisplays/nms/v1_11_R1/NmsManagerImpl.java#L43

Thanks,
Tim

**Comment by filoghost** [comment] 2016-12-24 13:55
I've tested with 1.11. At first it seems that Holographic Displays blocks slime spawning, but even after removing the plugin slimes wouldn't spawn. I was able to make them spawn at night in a swamp biome, with the plugin enabled. It looks like this issue has nothing to do with the plugin.

Also I can't use another ID because the client wouldn't be able to see and click the slimes (I tried).

**Comment by timbru31** [comment] 2016-12-24 15:00
It's not about spawning (naturally) but about spawners which have set the type to Slime. Spawners and eggs do no longer work and e.g. the spinning mob is empty.
Have you tested these use cases, too?

**Comment by timbru31** [comment] 2017-01-25 18:15
@filoghost - I'm getting numerous issues about slimes being broken. Could you re-investigate if you can solve your problem otherwise than misusing the slime entity?

**Comment by filoghost** [comment] 2017-02-06 12:31
@timbru31 I've taken a look at this issue (https://dev.bukkit.org/projects/silkspawners/issues/120) and done some tests. I'm unable to reproduce the issue or the problems that you mentioned, as you can see here https://gfycat.com/UnluckySerpentineHuman I'm using both HolographicDisplays and SilkSpawners. The slime spawner works (note: it seems to only work with low light levels and in the swamp biome) and I don't see slimeHolographicDisplays in the "/ss list".

CraftBukkit version: git-Spigot-b4417b8-3c48711 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by filoghost** [comment] 2017-02-06 14:23
After inspecting the NMS code a bit more (specifically: EntityTypes, RegistryMaterials, RegistryID) HolographicDisplays appears to overwrite the slime ID (that is 55) in the RegistryID. However, the getId method (that maps IDs to entity classes) is never referenced in the NMS code.

Are you using that method to retrieve the NMS entity class from its ID?

**Comment by filoghost** [comment] 2017-02-06 16:09
https://github.com/filoghost/HolographicDisplays/commit/f28607dab2096f048ca8a19d755f6703bd6047f5

**Comment by Managering** [comment] 2017-02-13 10:50
Could you make a compiled version please?

**Comment by filoghost** [comment] 2017-02-13 13:15
https://dev.bukkit.org/projects/holographic-displays/files/2381220 I had to make a release anyway, other bugs were fixed.

**Comment by filoghost** [comment] 2017-03-01 17:11
I'm closing this issue as it appears to be fixed, and nobody answered.

**Comment by OrrinWolf** [comment] 2018-01-23 02:58
I would like to report that, adding Holographic Displays to our server does indeed break the slimes from spawning from a slime spawner. Naturally spawned slimes function fine, but a crafted spawner, or a spawner given using the give command or the silkSpawner give command does not spawn slimes in -any- condition.

**Comment by Darkweasam** [comment] 2020-10-20 20:54
This still seems to be an issue in 1.16.3

**Comment by filoghost** [comment] 2020-11-04 17:02
I'm reopening this, probably related to #76

**Comment by TerdyTheTerd** [comment] 2021-02-15 04:57
Related to this, if I were to say change the ID used by the plugin to something else, say a mob that will not have its SilkSpawner enabled, would you expect there to be any issues with it? I am in need of a somewhat urgent workaround, but thought I would check before attempted to do it myself :D

**Comment by filoghost** [comment] 2021-12-08 15:33
The new beta doesn't use real entities anymore, so I can finally close this.

**Closed by filoghost** 2021-12-08 15:33 UTC
Labels: Bug
