### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JustJP2K** [filoghost/HolographicDisplays#401] opened 2021-01-20 12:29 UTC
https://pastebin.com/LZNKmCB2 

### Platform

- Server version 1.16.5
- Holographic Displays version 2.4.5: 
- ProtocolLib version, if installed 4.6.0: 
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...):
ViaVersion, ViaBackwards, Geyser

doubt thats the issue though since this error was even before i installed those plugins

**Comment by Kod3ntz** [comment] 2021-01-22 06:57
Also having this error. [https://pastebin.com/F7vgmvRg](https://pastebin.com/F7vgmvRg)

Purpur 1.16.5
HolographicDisplays 2.4.5
ProtocolLib 4.6.0-SNAPSHOT-b492
ViaVersion 3.2.1

**Comment by filoghost** [comment] 2021-01-24 14:16
Duplicate of #388

**Closed by filoghost** 2021-01-24 14:16 UTC
Labels: Bug
