### ISSUE TITLE
Add PlaceHolderAPI support or events?

### ISSUE THREAD

**Issue by Fernthedev** [filoghost/HolographicDisplays#100] opened 2018-09-08 18:52 UTC
Unless I missed something, I haven't seen anything related to PlaceHolderAPI support or events that get called when a hologram is made. Could this be added in the future?

**Comment by filoghost** [comment] 2018-09-11 10:44
I need to check if there could be perfomance issues, otherwise it will be added!

**Comment by Echoblast53** [comment] 2018-09-19 02:41
It was a very simple injection for me: since all you need from PlaceHolderAPI was to convert the customName found in protocol lib support from a unaffected string to a PlaceHolderAPI replaced string, similar to how {displayname} and {player} were replaced. The only issue is this: https://github.com/filoghost/HolographicDisplays/issues/101 (the player triggering ProtocolLib would be the oldest person on the server in the area). This probably needs to be fixed first, and I have no idea where to look.

**Comment by successed** [comment] 2019-06-13 10:48
why close ? we need this.

**Comment by filoghost** [comment] 2019-06-13 11:18
It's not closed. I just closed the other issue, that is a duplicate of this one.

**Comment by successed** [comment] 2019-06-14 02:52
oke, ty. we waiting for you.

**Comment by Echoblast53** [comment] 2019-06-14 07:25
So... did you find any performance issues? :)

**Comment by successed** [comment] 2019-07-03 15:14
we need this.http://prntscr.com/oa3is4

**Comment by Echoblast53** [comment] 2019-07-03 18:11
What is with the issue of constantly calling a placeholder api string
replacement? i've done that for my server and it seems stable.

**Comment by Fernthedev** [comment] 2019-07-03 18:43
Each placeholder has its own way of getting values, some have more heavy loads than others. It's probably not wise to be calling heavy loads every tick or whatever. Maybe have a config option to update the placeholder every few ticks or so?

**Comment by successed** [comment] 2019-07-17 22:44
we waiting...

**Comment by Echoblast53** [comment] 2019-07-21 19:42
> Each placeholder has its own way of getting values, some have more heavy loads than others. It's probably not wise to be calling heavy loads every tick or whatever. Maybe have a config option to update the placeholder every few ticks or so?
> Edit: Forgot to also mention, there could be MULTIPLE holograms doing this at once around a server that has other operations. Performance is pretty important when implementing something like this

If others can recklessly take care of placeholder caching (which probably is non existent), why can't you just follow suit then? Usually, scoreboards render per player, and they refresh X amount of game ticks...

**Comment by sgdc3** [comment] 2019-10-16 15:35
@Helcostr PRs are welcome, i see you already implemented this feature in your server

**Comment by Helcostr** [comment] 2019-10-18 01:47
> @Helcostr PRs are welcome, I see you already implemented this feature in your server

It's a sloppy PR, since I wasn't thinking about designing it to be elegant, and just spaghetti it in. I'll re-educate myself and work on a PR when I got the time (I was looking to flog for the performance evaluation).

**Comment by Chazza** [comment] 2019-12-12 22:09
I've already added it ;) https://github.com/filoghost/HolographicDisplays/pull/239

**Comment by filoghost** [comment] 2021-12-08 15:32
Added in the new beta version.

**Closed by filoghost** 2021-12-08 15:32 UTC
Labels: Enhancement
