### ISSUE TITLE
Porotocollib + HolographicDisplays error

### ISSUE THREAD

**Issue by andris155** [filoghost/HolographicDisplays#193] opened 2019-07-28 14:59 UTC
Paper 1.14.4
```
[10:13:40] [User Authenticator #80/INFO]: UUID of player barbi14 is 48dfcb28-a33c-3830-a194-792dc78bee30
[10:13:40] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception number 16384 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:278) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1386) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1246) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:817) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:999) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1134) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:594) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1166) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayer0(WorldServer.java:953) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.WorldServer.addPlayerJoin(WorldServer.java:929) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:229) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-146]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 13.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:418) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 43 more
```

**Comment by Cryptite** [comment] 2019-07-31 14:12
Can confirm, also get this.

**Comment by mibby** [comment] 2019-08-01 02:01
RE: https://github.com/filoghost/HolographicDisplays/issues/135

**Comment by Rixafy** [comment] 2019-08-05 07:00
Use latest version of ProtocolLib, http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/.

**Comment by mibby** [comment] 2019-08-05 08:48
@Rixafy Stop posting this comment on issues. Newest version of ProtocolLib does _not_ fix the issue.

Problem is described here.
https://github.com/filoghost/HolographicDisplays/issues/135#issuecomment-511949657

Problem is reported here.
https://github.com/dmulloy2/ProtocolLib/issues/663

**Comment by Rixafy** [comment] 2019-08-05 09:52
Sorry, I had the same issue yesterday, and after protocollib update, it dissapears

**Comment by filoghost** [comment] 2019-08-11 12:20
Duplicate of #135

**Closed by filoghost** 2019-08-11 12:20 UTC
