### ISSUE TITLE
Lines being cut off

### ISSUE THREAD

**Issue by zeronerve** [filoghost/HolographicDisplays#228] opened 2019-09-25 13:24 UTC
The text in my holo is being cut off at various lengths. See the attached image. I'm running Paper 1.13.2 with the latest version of HD. Is there a line length limit?

Here's the code that generates the holo. I've tried this without StringBuilder with no change. I'm not using StringBuilder for any useful purpose, other than to see if it magically fixed the problem.

I'm using a singlar/plural method sp() to return appropriate labels.

If I log the textLine String, it returns the proper length.

If I remove all the ChatColors, the problem still occurs.

```java
      ...
while (leadersIterator.hasNext()) {

      Leader l = (Leader) leadersIterator.next();
      
      StringBuilder textLine = new StringBuilder();
      
      textLine.append(ChatColor.YELLOW + "#" + i + " " + ChatColor.GOLD + l.getUsername() + " : ");
      
      textLine.append("" + ChatColor.WHITE + l.getPoints() + " " + ChatColor.LIGHT_PURPLE + sp(l.getPoints(), "Point", "Points"));
      
      textLine.append(" " + ChatColor.WHITE + l.getCaptures() + " " + ChatColor.LIGHT_PURPLE + sp(l.getCaptures(), "Cap", "Caps"));
      
      textLine.append(" " + ChatColor.WHITE + l.getWins() + " " + ChatColor.LIGHT_PURPLE + sp(l.getWins(), "Win", "Wins"));
      
      textLine.append(" " + ChatColor.WHITE + l.getKills() + " "  + ChatColor.LIGHT_PURPLE + sp(l.getKills(), "Kill", "Kills"));
      
      textLine.append(" " + ChatColor.WHITE + l.getDeaths() + " " + ChatColor.LIGHT_PURPLE + sp(l.getDeaths(), "Death", "Deaths"));
      
      textLine.append(" " + ChatColor.WHITE + l.getRecoveries() + " " + ChatColor.LIGHT_PURPLE + sp(l.getRecoveries(), "Recovery", "Recoveries"));
      
      textLine.append(" " + ChatColor.WHITE + l.getGamesPlayed() + " " + ChatColor.LIGHT_PURPLE + sp(l.getGamesPlayed(), "Game", "Games"));
      
      TextLine line3 = leaderboardHolo.appendTextLine(textLine.toString());
      
      if (i > 3) leadersIterator.remove();
      
      i++;
      
}
```

![holo](https://user-images.githubusercontent.com/34899120/65604946-e6e97680-df6d-11e9-9284-3593b5dd5842.png)
 
<img width="964" alt="Annotation 2019-09-25 083036" src="https://user-images.githubusercontent.com/34899120/65605512-d1c11780-df6e-11e9-8c26-fafa20214924.png">

**Comment by zeronerve** [comment] 2019-10-05 15:16
Still having trouble with this. Any ideas?

**Comment by filoghost** [comment] 2019-10-20 16:52
Before setting the line, could you get the string and check the length? The current length limit is 300, counting colors too.

**Comment by zeronerve** [comment] 2019-10-20 17:17
Thanks for your reply! The lines are only cut off in 1.8.9. in 1.13
everything is fine. is there a workaround?

**Comment by filoghost** [comment] 2019-10-21 12:31
I did some testing on 1.8.9. There is a limit of 256 characters, including colors, client side, and that cannot be bypassed. However, I've counted the characters in the screenshot and the total is 64 including colors. Are you using the vanilla 1.8.9 client?

**Comment by zeronerve** [comment] 2019-10-21 13:02
using vanilla yes. I've also tried it with Badlion Client (1.8.9) and with
Vanilla 1.8.9 + Optifine. All show cutoff lines. If I use Vanilla 1.13.2 it
shows the entire line.

This is the code I'm using to build the holo...


this.leaderboardHolo = HologramsAPI.createHologram(plugin, this.leaderboardLoc);
TextLine line1 = leaderboardHolo.appendTextLine("All-time Leaders");
TextLine line2 = leaderboardHolo.appendTextLine("------------------------");
int i = 1;
ListIterator leadersIterator = leaders.listIterator();

while (leadersIterator.hasNext()) {
    Leader l = (Leader) leadersIterator.next();

    String spPoints = sp(l.getPoints(), "Point", "Points");
    String spCaps= sp(l.getCaptures(), "Cap", "Caps");
    String spWins = sp(l.getWins(), "Win", "Wins");
    String spKills = sp(l.getKills(), "Kill", "Kills");
    String spDeaths = sp(l.getDeaths(), "Death", "Deaths");
    String spRecoveries = sp(l.getDeaths(), "Recovery", "Recoveries");

    StringBuilder textLine = new StringBuilder();
    textLine.append(ChatColor.YELLOW + "#" + i + " " + ChatColor.GOLD
+ l.getUsername() + " : ");
    textLine.append("" + ChatColor.WHITE + l.getPoints() + " " +
ChatColor.LIGHT_PURPLE + spPoints);
    textLine.append(" " + ChatColor.WHITE + l.getCaptures() + " " +
ChatColor.LIGHT_PURPLE + spCaps);
    textLine.append(" " + ChatColor.WHITE + l.getWins() + " " +
ChatColor.LIGHT_PURPLE + spWins);
    textLine.append(" " + ChatColor.WHITE + l.getKills() + " "  +
ChatColor.LIGHT_PURPLE + spKills);
    textLine.append(" " + ChatColor.WHITE + l.getDeaths() + " " +
ChatColor.LIGHT_PURPLE + spDeaths);
    textLine.append(" " + ChatColor.WHITE + l.getRecoveries() + " " +
ChatColor.LIGHT_PURPLE + spRecoveries);

    plugin.log(textLine.toString());
    TextLine line3 = leaderboardHolo.appendTextLine(textLine.toString());
    if (i > 3) leadersIterator.remove();
    i++;
}

**Comment by zeronerve** [comment] 2019-10-21 13:35
It looks like this in 1.13 ...

[image: image.png]

**Comment by zeronerve** [comment] 2019-10-21 13:36
I must add that the last screen i sent was after modifying some of the
fields being displayed (percent wins, etc.). Problem still exists in 1.8.9.

**Comment by zeronerve** [comment] 2019-10-21 14:47
supporting 1.8.9 is important to me since we have a group of players with
PVP focus. any ideas?

**Comment by filoghost** [comment] 2019-10-21 16:13
The image you are talking about was not uploaded. About 1.8.9 vs 1.13.2, are you talking about the client versions only? What version is the server running?

**Comment by zeronerve** [comment] 2019-10-21 18:15
The server is 1.13.2 using Paper. With protocolsupport.

**Comment by filoghost** [comment] 2019-10-21 19:29
I found the issue in ProtocolSupport's code: https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/typeremapper/entity/metadata/types/base/LivingEntityMetadataRemapper.java#L17

It incorrectly limits the nametag to 64 characters, like it was in 1.6. Please open an issue on [their repository](https://github.com/ProtocolSupport/ProtocolSupport/issues). I'm closing this one, as the bug is not caused by Holographic Displays.

**Closed by filoghost** 2019-10-21 19:29 UTC

**Comment by zeronerve** [comment] 2019-10-22 00:08
Thank you!

**Comment by zeronerve** [comment] 2019-10-22 00:11
Do you know what Class handles this in protocolsupport?

**Comment by filoghost** [comment] 2019-10-22 12:24
It's the one I linked before
