### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TheBlueKyanite** [filoghost/HolographicDisplays#153] opened 2019-06-04 04:18 UTC
Hello, sometimes when a player is near a hologram the following exception occurs and the server crashes.
`java.lang.IllegalAccessError: class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand tried to access private field net.minecraft.server.v1_14_R1.Entity.bukkitEntity (com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @557302ac; net.minecraft.server.v1_14_R1.Entity is in unnamed module of loader 'app')
	at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206)
	at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1149)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:372)
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Note: This error occurs on the latest PaperSpigot build with the latest Snapshot of HolographicDisplays

**Comment by filoghost** [comment] 2019-06-04 11:46
Duplicate of https://github.com/filoghost/HolographicDisplays/issues/153

**Closed by filoghost** 2019-06-04 11:46 UTC
Labels: Duplicate
