### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EliteTrollingG** [filoghost/HolographicDisplays#403] opened 2021-01-21 17:41 UTC
### Description
No in game errors, just every couple seconds around 10 lines of errors pop up in console.

### How to reproduce
Literally no clude

### Platform

Paper 1.16.5
2.4.5
v4.6.0-SNAPSHOT-b492
No

### Additional context
![Screenshot 2021-01-21 105252](https://user-images.githubusercontent.com/60861809/105389517-8b6cde80-5bdd-11eb-8179-d0b9af82cb49.png)

**Comment by Kod3ntz** [comment] 2021-01-22 06:56
Also having this error. [https://pastebin.com/F7vgmvRg](https://pastebin.com/F7vgmvRg)

Purpur 1.16.5
HolographicDisplays 2.4.5
ProtocolLib 4.6.0-SNAPSHOT-b492
ViaVersion 3.2.1

**Comment by filoghost** [comment] 2021-01-24 14:17
Duplicate of #388

**Closed by filoghost** 2021-01-24 14:17 UTC
Labels: Bug
