### ISSUE TITLE
HolographicDisplays 900ms constant tick causing lag

### ISSUE THREAD

**Issue by Loonyy** [filoghost/HolographicDisplays#452] opened 2021-05-06 08:52 UTC
### Description

We are getting HD lag. 
561% of tick in the space of 10 mins
https://imgur.com/a/Lc4cWGw

For the past week, we've been getting a 900ms tick every so often which causes freezes in-game for players. This is monitored through Spark: https://i.imgur.com/GOvAWTl.png
Even when I am the only one on the server and not near any Holograms, this still happens.

### How to reproduce

Just be logged onto the eserver

### Platform

- Server version (output of `/version`): 
- Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Holographic Displays version (check with `/hd`): 
- Holographic Displays v2.4.6-SNAPSHOT-b163 by filoghost
- ProtocolLib version, if installed (check with `/protocol version`): 
- ProtocolLib v4.6.0-SNAPSHOT
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): 
- ViaVersion & ViaBackwards Version: 3.2.1

### Additional context

https://timings.aikar.co/?id=fa8a529aa52b42bca6e7eeeb828bdbf9
https://spark.lucko.me/ptKzFkxTvp
config: https://pastebin.com/qUTuM4GC

**Comment by filoghost** [comment] 2021-06-14 21:43
There's one or more external placeholders slowing everything. Try removing plugins that add them to find the cause. Closing this as it's not caused by Holographic Displays itself.

**Closed by filoghost** 2021-06-14 21:43 UTC
Labels: Bug
