### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by WarnDa** [filoghost/HolographicDisplays#533] opened 2021-12-06 13:33 UTC
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** (and **ProtocolLib** if installed) to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

The plugin consumes a lot of server tick, a part is from placeholders

### How to reproduce

Run the plugin with some holograms and players
Add placeholders on holograms
Do a spark.

### Server version

git-Airplane-12     1.16.5-R0.1-SNAPSHOT

### Holographic Displays version

3.0.0-SNAPSHORT from 2 december

### ProtocolLib version (if installed)

4.7.0

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion

### Additional information

I got only 10 holograms.
<img width="738" alt="Screenshot_199" src="https://user-images.githubusercontent.com/31826333/144854982-48a6eacf-148f-4ede-9f82-03ace0cbd843.png">

The spark : 
https://spark.lucko.me/lN6EveLIbT

**Comment by WarnDa** [comment] 2021-12-10 17:15
This still happen on the latest version uploaded on bukkit.
<img width="745" alt="Screenshot_231" src="https://user-images.githubusercontent.com/31826333/145614500-4c69515a-22f6-4247-8015-b9abacfc3724.png">

**Comment by ZConnorZ** [comment] 2021-12-11 10:40
I agree, I have a problem too. Because of this, it is not possible to update the server to 1.18 (This will kill the server just) :cry:

**Comment by JHarris12345** [comment] 2021-12-12 17:24
I can confirm this is SUPER laggy https://gyazo.com/650474f8d80c18bf103e878b1b3c6b6c

**Comment by JHarris12345** [comment] 2021-12-12 17:35
Another spark https://spark.lucko.me/649KcasLRw

**Comment by JHarris12345** [comment] 2021-12-12 17:41
I believe this could be fixed by allowing an update placeholder like {slow} etc that updates the placeholder at a custom time (as not every placeholder needs updating constantly)

**Comment by ZConnorZ** [comment] 2021-12-12 17:41
Try the plugin: 'Decent Holograms'

**Comment by JHarris12345** [comment] 2021-12-12 20:24
I have looked into it. Just need a few plugins to fix their dependencies for it before switching

**Comment by ZConnorZ** [comment] 2021-12-12 20:40
You can use 2 plugins :)

**Comment by JHarris12345** [comment] 2021-12-12 22:28
Could do but would rather not. If holographci displays just let us add a refresh rate for different holos with a config option, it would be ideal

**Comment by filoghost** [comment] 2021-12-24 15:50
I found and fixed some sources of lag (also PlaceholderAPI itself, but I cannot optimize it. I can only slow down the refresh rate). Please try the latest dev build, and if you can send another Spark report, I don't have an active server to make real benchmarks.

**Comment by WarnDa** [comment] 2021-12-24 16:43
I'll do a spark tomorrow.

Currently using Paul's custom version and it works pretty fine !
https://github.com/TECHNOVE/HolographicDisplays
![image](https://user-images.githubusercontent.com/31826333/147365216-86614cd2-b544-4e41-aec4-9c3b84dec4aa.png)

**Comment by filoghost** [comment] 2021-12-24 17:41
That's an old version. Most of the work is done by Bukkit itself to manage entities, so you don't see the actual workload.

**Comment by JHarris12345** [comment] 2021-12-24 18:49
@filoghost why not do the change in #540 because my version doesnt really lag at all and I have quite intense placeholders

**Comment by WarnDa** [comment] 2021-12-25 02:03
![image](https://user-images.githubusercontent.com/31826333/147375837-8faa2aaf-f5c5-4c14-866f-6bcdc701c7dc.png)
On your latest dev build placeholders do not work at all

**Comment by WarnDa** [comment] 2021-12-25 02:10
I got only 10 placeholders, currently 20 people only (4 am) and plugin still take almost 2% server tick
![image](https://user-images.githubusercontent.com/31826333/147375909-6c86d17d-edc1-458b-bb0f-f89737d25973.png)

It's 5x more my top 3 other heavier plugins

**Comment by JHarris12345** [comment] 2021-12-25 02:23
> ![image](https://user-images.githubusercontent.com/31826333/147375837-8faa2aaf-f5c5-4c14-866f-6bcdc701c7dc.png)
> On your latest dev build placeholders do not work at all

Format is {papi: <placeholder>}

**Comment by WarnDa** [comment] 2021-12-25 02:29
> > ![image](https://user-images.githubusercontent.com/31826333/147375837-8faa2aaf-f5c5-4c14-866f-6bcdc701c7dc.png)
> > On your latest dev build placeholders do not work at all
> 
> Format is {papi: placeholder}

I got an issue with this :/
One of my placeholders get an } inside : 
> papi:progress_percentage_{storestats_goal_progress_29981}_m:100}

So it doesn't work and create an issue

**Comment by JHarris12345** [comment] 2021-12-25 02:46
> > > ![image](https://user-images.githubusercontent.com/31826333/147375837-8faa2aaf-f5c5-4c14-866f-6bcdc701c7dc.png)
> > > On your latest dev build placeholders do not work at all
> > 
> > 
> > Format is {papi: placeholder}
> 
> I got an issue with this :/ One of my placeholders get an } inside :
> 
> > papi:progress_percentage_{storestats_goal_progress_21}_m:100}
> 
> So it doesn't work for me

You havent put a { before papi. Do this:

{papi:

if it doesnt work then the placeholder needs ro be changed to remove those {}. Thats a really stupid placeholder

**Comment by WarnDa** [comment] 2021-12-25 14:56
> > > > ![image](https://user-images.githubusercontent.com/31826333/147375837-8faa2aaf-f5c5-4c14-866f-6bcdc701c7dc.png)
> > > > On your latest dev build placeholders do not work at all
> > > 
> > > 
> > > Format is {papi: placeholder}
> > 
> > 
> > I got an issue with this :/ One of my placeholders get an } inside :
> > > papi:progress_percentage_{storestats_goal_progress_21}_m:100}
> > 
> > 
> > So it doesn't work for me
> 
> You havent put a { before papi. Do this:
> 
> {papi:
> 
> if it doesnt work then the placeholder needs ro be changed to remove those {}. Thats a really stupid placeholder

I di, just forgot to write it, but it doesn't work

**Comment by WarnDa** [comment] 2021-12-25 15:02
The plugin with more players
![image](https://user-images.githubusercontent.com/31826333/147387851-97b9b6e7-1845-4756-a4db-740380e45911.png)

**Comment by WarnDa** [comment] 2021-12-25 15:08
Where is the settings to edit placeholders refresh time ?
Because this is what is heavy, everytime placeholder is refreshed, it needs to resend all the packets to players.

**Comment by JHarris12345** [comment] 2021-12-25 15:17
I forked a version where you can edit the refresh rates of every individual placeholder. Hopefully its added in a dev build. Check #540 for what I did because you can just copy it if you fork it too. Took 10 seconds

**Comment by WarnDa** [comment] 2021-12-25 15:29
> 

I can't event find the settings to modify "global refresh time"

**Comment by JHarris12345** [comment] 2021-12-25 15:30
Idk where that setting is coz as I said I forked my own version and added a system where I can change them individually. The code I changed is in the post I tagged if u want to code it

**Comment by WarnDa** [comment] 2021-12-25 15:33
Even without ANY placeholders the plugin is really heavy : 
![image](https://user-images.githubusercontent.com/31826333/147388411-8a035538-23cd-47da-990c-6caccfbdfff5.png)

**Comment by WarnDa** [comment] 2021-12-26 12:59
![image](https://user-images.githubusercontent.com/31826333/147408842-1e9df83a-3f61-4f45-a4aa-37eb865e468d.png)
Even without ANY placeholders the plugin is really heavy :
I just get basic holograms wirthout anything inside.

**Comment by filoghost** [comment] 2022-01-02 09:57
Please always post links of the spark reports and the exact version you are using. It's difficult otherwise to pinpoint the cause of lag.

**Comment by WarnDa** [comment] 2022-01-02 13:53
> Please always post links of the spark reports and the exact version you are using. It's difficult otherwise to pinpoint the cause of lag.

Here is the spark : https://spark.lucko.me/eMhCtYcL0P

And I'm using this version (so your latest 'optimisation' update
![image](https://user-images.githubusercontent.com/31826333/147877909-90d55697-ee29-40ed-85eb-7dd3a6c83809.png)

**Comment by filoghost** [comment] 2022-02-05 11:17
Sorry but, can you please test again with the latest dev build? The report doesn't show the exact cause (only the Java method), so I have to do some guesses.

**Comment by WarnDa** [comment] 2022-02-05 13:04
I'll try in 48hr

**Comment by WarnDa** [comment] 2022-02-05 13:24
Still heavy
![image](https://user-images.githubusercontent.com/31826333/152643922-cbacb478-bdbe-4a4d-9997-2c58ad4da0e3.png)
https://spark.lucko.me/rZmbqhDOwm

(Using latest dev build)

**Comment by filoghost** [comment] 2022-02-05 15:31
Thanks, it is now more detailed. I'll see what I can do, in the previous version this overhead was hidden since the plugin was spawning real entities.

**Closed** 2023-01-10 10:34 UTC
Labels: Bug
